### PR TITLE
Add ability to configure Cropperjs

### PR DESCRIPTION
**Pull request by mikaelpopowicz**
This PR adds ability to configure cropperjs.

```php
<?php

declare(strict_types=1);

namespace App\nova;

use Oneduo\NovaFileManager\FileManager;

class User extends Resource
{
    // ...

    public function fields(NovaRequest $request)
    {
        return [
            // ...

            FileManager::make('Image')
                ->cropperOptions([
                    'aspectRation' => 16/9,
                ]),
        ];
    }
}
```

You can find the available options at [Cropper.js repository](https://github.com/fengyuanchen/cropperjs/blob/main/README.md#options).

Closes https://github.com/oneduo/nova-file-manager/issues/146

### CODE REVIEW

**Review by Rezrazi — APPROVED** [review]

**Comment by Elvinca** [comment]
Hey @mikaelpopowicz, I tried it out and it doesn't seem to work. What would be the steps to debug my issue ? I did it exactly like u did in the PR.

**Comment by Elvinca** [comment]
Hey @mikaelpopowicz, thanks for the PR, works smoothly. One more question. Is there a way to do it globally instead of setting it inside of each field of resource class? Also now when I go straight into FileManager (not accessing by some field inside resource), it doesn't work.

Thanks

**Comment by mikaelpopowicz** [comment]
Hi @Elvinca 

If you want to configure multiple fields and/or tool with same settings, you use the [wrapper feature](https://oneduo.github.io/nova-file-manager/field.html#third-party-compatibility).

> Also now when I go straight into FileManager (not accessing by some field inside resource), it doesn't work.

May you explain or elaborate by creating a new issue if needed ?

**Comment by Elvinca** [comment]
To elaborate more specifically, let's assume we have resource **User**, which has registered field **Profile picture** as FileManager field. I want to set the cropper to 16/9, so I call  **->cropperOptions([...])** during registering. Now when I open edit and open filemanager trough this field, **Cropper works perfectly fine.**

But when I don't open filemanager trough some field in resource edit BUT open the **global manager** directly trough sidebar, cropper doesnt have 16/9 set as default. I need it to be set also there.

Is it clearer now ? I can also provide video if needed.

Thanks for your assistance.

**Comment by mikaelpopowicz** [comment]
You may call the `cropperOptions` on the tool registration.

**Pull request merged**
